#pragma config(Sensor, in1,    agl_lifter,      sensorAnalog)
#pragma config(Sensor, in2,    agl_arm,        sensorAnalog)
#pragma config(Sensor, in3,    agl_wiper,      sensorAnalog)
#pragma config(Sensor, in4,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  enc_moveL,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  enc_moveR,      sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  enc_updown,     sensorQuadEncoder)
#pragma config(Motor,  port1,           mtr_wiper,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           mtr_RF,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           mtr_RB,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           mtr_LF,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           mtr_LB,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           mtr_updownR,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mtr_updownL,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           mtr_lifter,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           mtr_arm,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          mtr_claw,      tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/********* Debug Selection *********/
#define ROUTE_DATA 3			// Auto Route
#define CAPTURE_AUTO 1			// Capture Mode
bool slowacc = true; 			// Slow Acceleration
bool antislip = false; 			// Reduce Move Slip
bool updownpid = true; 			// Updown PID Status
bool wiperpid = true;      		// Wiper PID Status
bool armpid = true; 			// Arm PID Status
int control_duration = 25;  	// Speed Calculate Duration
int pid_control_duration = 10;  // PID Control Duration
/**************** END *****************/

#include "Include.c"

task main()
{
	Initialization();
	startTask(Thread_Control);
	while(1) wait1Msec(100);
}
